### ISSUE TITLE
Training Pipeline

### ISSUE THREAD

**Issue by kjpou1** [kjpou1/convolution-patterns#3]
# 🧠 Convolution CV – Training Pipeline Summary

## 🎯 Goal

Train a transfer learning-based CNN to classify indicator chart patterns from image data, using a modular, YAML-driven architecture.

---

## 🔁 Pipeline Overview

```

CLI ➜ TrainPipeline
├── ImageDatasetService      # Loads raw tf.data.Dataset from disk
├── TransformService         # Applies resize, normalize, augment
├── ModelBuilderService      # Builds Keras model from config
├── TrainingLoggerService    # Logs metrics, saves plots and model
└── Keras Training Loop      # Trains model with callbacks

````

---

## 🧱 Component Responsibilities

| 🧩 Component            | 📋 Description                                                |
|------------------------|--------------------------------------------------------------|
| `TrainPipeline`        | Orchestrates dataset loading, transforms, model build, training, logging |
| `ImageDatasetService`  | Loads raw datasets from `artifacts/data/processed/{split}/...` |
| `TransformService`     | Applies preprocessing and augmentations using config         |
| `ModelBuilderService`  | Builds model from `custom_head.layers` and backbone          |
| `TrainingLoggerService`| Logs metrics, plots, YAML config, and model checkpoints      |

---

## 🧾 YAML Config Structure

```yaml
model:
  backbone: EfficientNetB0
  freeze_base: true
  custom_head:
    layers:
      - type: GlobalAveragePooling2D
      - type: Dense
        units: 256
        activation: relu
      - type: Dropout
        rate: 0.3
      - type: Dense
        units: num_classes
        activation: softmax

training:
  batch_size: 32
  epochs: 50
  optimizer:
    type: adam
    lr: 0.001
  loss: categorical_crossentropy
  metrics: [accuracy]
````

---

## 📦 Output Artifacts

Saved to: `artifacts/training_runs/{model_name}/`

```
training_config.yaml
training_history.csv
metrics.json
loss_plot.png
accuracy_plot.png
model_best.h5
```

---

## ⚙️ Design Features

* ✅ Modular service architecture
* ✅ Flexible layer composition via `custom_head.layers`
* ✅ Clear separation of loading and transformation logic
* ✅ MLflow-ready (integration planned via TODO hooks)
* ✅ CLI-driven and fully YAML-configurable
